version: '2'
services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
    testserver:
        image: testserver
    curl:
        image: appropriate/curl 
        entrypoint: sh -c  "sleep 3 && curl -XPOST testserver:8080/helloworld -d '{\"name\":\"mk\"}'"